name: Arrange android keystore file

inputs:
  jks_base64:
    description: 'Base64 encoded keystore file'
    required: true
  key_password:
    description: 'Key password'
    required: true
  key_alias:
    description: 'Key alias'
    required: true
  store_password:
    description: 'Store password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create keystore file
      env:
        ANDROID_KEY_JKS_BASE64: ${{ inputs.jks_base64 }}
      run: |
        echo -n $ANDROID_KEY_JKS_BASE64 | base64 --decode > android/app/keystore.jks
      shell: bash

    - name: Create key.properties file
      env:
        ANDROID_KEY_PASSWORD: ${{ inputs.key_password }}
        ANDROID_KEY_ALIAS: ${{ inputs.key_alias }}
        ANDROID_STORE_PASSWORD: ${{ inputs.store_password }}
      run: |
        echo "storeFile=./keystore.jks" > android/key.properties
        echo "storePassword=$ANDROID_STORE_PASSWORD" >> android/key.properties
        echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
        echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
      shell: bash
