name: Arrange keystore file

runs:
  using: "composite"
  steps:
    - name: Create keystore file
      env:
        ANDROID_KEY_JKS_BASE64: ${{ secrets.ANDROID_KEY_JKS_BASE64 }}
      run: |
        echo -n $ANDROID_KEY_JKS_BASE64 | base64 --decode > android/app/upload.jks
      shell: bash

    - name: Create key.properties file
      env:
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
      run: |
        echo "storeFile=./upload.jks" > android/key.properties
        echo "storePassword=$ANDROID_STORE_PASSWORD" >> android/key.properties
        echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
        echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
      shell: bash
