name: Deliver

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write

env:
  APP_NAME: TouchSender

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arrange keystore file
        uses: ./.github/actions/arrange-keystore-file
        with:
          jks_base64: ${{ secrets.ANDROID_KEY_JKS_BASE64 }}
          key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}
          key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          store_password: ${{ secrets.ANDROID_STORE_PASSWORD }}

      - name: Get version from pubspec.yaml
        run: |
          echo "RESOLVED_VERSION=$(sed -n 's/^version: *\([^ ]*\) *$/\1/p' pubspec.yaml)" >> $GITHUB_ENV

      - name: Set APK name
        run: |
          echo "APK_NAME=${{ env.APP_NAME }}-${{ env.RESOLVED_VERSION }}.apk" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Build apk
        run: |
          flutter build apk --release

      - name: Upload to release note
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{ env.APK_NAME }}
          gh release upload v${{ env.RESOLVED_VERSION }} \
              build/app/outputs/flutter-apk/${{ env.APK_NAME }} \
              --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
