name: CI(Build and Test)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Arrange keystore file
        uses: ./.github/actions/arrange-keystore-file

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - run: flutter build apk
