name: CI(Build and Test)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Arrange keystore file
        uses: ./.github/actions/arrange-keystore-file
        with:
          jks_base64: ${{ secrets.ANDROID_KEY_JKS_BASE64 }}
          key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}
          key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          store_password: ${{ secrets.ANDROID_STORE_PASSWORD }}


      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - run: flutter build apk
